/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author nikes
 */
public class NavigationBar extends javax.swing.JPanel {

    // --- ADD THESE 3 VARIABLES ---
    private String username;
    private int userId;
    private boolean isAdmin;

    /**
     * Creates new form NavigationBar
     */
    public NavigationBar() {
        initComponents();
    }

    // --- ADD THIS METHOD SO MAIN PAGES CAN PASS DATA ---
    public void setUserData(String username, int userId, boolean isAdmin) {
        this.username = username;
        this.userId = userId;
        this.isAdmin = isAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Logo_productcatalog1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(58, 125, 68));
        jPanel3.setMinimumSize(new java.awt.Dimension(1550, 48));
        jPanel3.setLayout(null);

        Logo_productcatalog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/rewearLogo.jpeg"))); // NOI18N
        jPanel3.add(Logo_productcatalog1);
        Logo_productcatalog1.setBounds(10, 10, 220, 30);

        jButton9.setBackground(new java.awt.Color(58, 125, 68));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/bellbtn.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 125, 38)));
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel3.add(jButton9);
        jButton9.setBounds(1420, 0, 50, 50);

        jButton10.setBackground(new java.awt.Color(58, 125, 68));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/userrIcon.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 125, 68)));
        jButton10.setMinimumSize(new java.awt.Dimension(44, 45));
        jButton10.setPreferredSize(new java.awt.Dimension(44, 45));
        jButton10.addActionListener(this::jButton10ActionPerformed);
        jPanel3.add(jButton10);
        jButton10.setBounds(1370, 0, 44, 50);

        jButton11.setBackground(new java.awt.Color(58, 125, 68));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/cartticon.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 125, 68)));
        jButton11.setPreferredSize(new java.awt.Dimension(44, 45));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(this::jButton11ActionPerformed);
        jPanel3.add(jButton11);
        jButton11.setBounds(1477, 6, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // --- ADDED NOTIFICATION LOGIC ---
        view.Notification_page notifWindow = new view.Notification_page(); 
        notifWindow.setVisible(true);
        notifWindow.setLocationRelativeTo(null);
        
        // Close current window
        java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (currentWindow != null) {
            currentWindow.dispose();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (isAdmin) {
            new view.AdminDashboard(username).setVisible(true);
        } else {
            new view.UserDashboard(username, userId).setVisible(true);
        }
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       view.Cart cartWindow = new view.Cart(this.userId); 
    cartWindow.setVisible(true);
    cartWindow.setLocationRelativeTo(null);
     
    // Close current window
    java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (currentWindow != null) {
        currentWindow.dispose();
    }

    
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        System.out.println("Cart button clicked!"); // This helps us test
    
    view.Cart cartWindow = new view.Cart(this.userId); 
    cartWindow.setVisible(true);
    cartWindow.setLocationRelativeTo(null);
    
    java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (currentWindow != null) {
        currentWindow.dispose();
    }
    }//GEN-LAST:event_jButton11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo_productcatalog1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}

